2023-12-01 06:32:28,692 - ERROR - Database connection failed, error is: name 'mongo_url' is not defined
2023-12-01 06:33:02,890 - ERROR - Database connection failed, error is: name 'mongo_url' is not defined
2023-12-01 06:39:22,802 - ERROR - Database connection failed, error is: name 'mongo_url' is not defined
2023-12-01 06:40:23,801 - INFO - Database connected.
2023-12-01 06:40:48,341 - INFO - Database connected.
2023-12-01 06:47:47,819 - INFO - Database connected.
2023-12-01 06:49:38,610 - INFO - Database connected.
2023-12-01 06:50:18,575 - INFO - Database connected.
2023-12-01 07:30:19,026 - ERROR - Database connection failed, error is: host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65698b6c29874d72b496730a, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 07:33:34,827 - ERROR - Database connection failed, error is: host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65698c30213f41e43f9441d4, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 07:35:09,533 - ERROR - Database connection failed, error is: host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65698c8feec8c22f722f7f5d, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27020) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 07:38:41,528 - ERROR - Database connection failed, error is: host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65698d6364d28a5a23c704d7, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27020) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 07:39:22,094 - ERROR - Database connection failed, error is: host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65698d8bc58f37aa01c760ff, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27020) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 10:18:00,353 - ERROR - Database connection failed, error is: host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6569b2b91032efd2fca41a7e, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27020) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 10:19:37,107 - ERROR - Database connection failed, error is: host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6569b31a36aeb6c0734938ca, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27020) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27020: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 10:20:19,459 - ERROR - Database connection failed, error is: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
2023-12-01 10:21:33,005 - ERROR - Database connection failed, error is: host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6569b38e56d2fff381008834, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 10:23:46,283 - ERROR - Database connection failed, error is: host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6569b414aefd0a30559fe247, topology_type: Unknown, servers: [<ServerDescription ('host.docker.internal', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('host.docker.internal:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2023-12-01 10:25:27,116 - ERROR - Database connection failed, error is: command listIndexes requires authentication, full error: SON([('ok', 0.0), ('errmsg', 'command listIndexes requires authentication'), ('code', 13), ('codeName', 'Unauthorized')])
2023-12-01 10:27:52,906 - INFO - Database connected.
2023-12-01 10:29:57,850 - INFO - Database connected.
2023-12-01 10:33:16,700 - INFO - Database connected.
